import styled from 'styled-components';

export const Wrapper = styled.div`
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  flex: 1;
`;

export const LoaderContainer = styled.div`
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: ${(props) => props.theme.background};

  .loader {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0;
  }

  .loader div {
    position: absolute;
    width: 22.5px;
    box-sizing: content-box;
  }

  .loader div:nth-child(1) {
    left: 26.25px;
    background: ${(props) => props.theme.secondary};
    animation: ldio-69tp37x3xb5-1 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
    animation-delay: -0.2s;
  }

  .loader div:nth-child(2) {
    left: 63.75px;
    background: #ddd;
    animation: ldio-69tp37x3xb5-2 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
    animation-delay: -0.1s;
  }

  .loader div:nth-child(3) {
    left: 101.25px;
    background: ${(props) => props.theme.primary};
    animation: ldio-69tp37x3xb5-3 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
    animation-delay: undefineds;
  }

  @keyframes ldio-69tp37x3xb5-1 {
    0% {
      top: 27px;
      height: 96px;
    }
    50% {
      top: 45px;
      height: 60px;
    }
    100% {
      top: 45px;
      height: 60px;
    }
  }
  @keyframes ldio-69tp37x3xb5-2 {
    0% {
      top: 31.499999999999993px;
      height: 87.00000000000001px;
    }
    50% {
      top: 45px;
      height: 60px;
    }
    100% {
      top: 45px;
      height: 60px;
    }
  }
  @keyframes ldio-69tp37x3xb5-3 {
    0% {
      top: 36px;
      height: 78px;
    }
    50% {
      top: 45px;
      height: 60px;
    }
    100% {
      top: 45px;
      height: 60px;
    }
  }
`;

// Code generated by https://loading.io/
